version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./app.dockerfile
    ports:
      - 7070:7070
    volumes:
      - .:/app
    depends_on:
      database:
        condition: service_healthy
    container_name: loan-app
    environment:
      - 'DB_PORT=3306'
      - 'DB_HOST=database'

  database:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: loan-db
    container_name: golang-loan-db
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 5
    volumes:
      - golang-docker-data:/var/lib/mysql
  
  adminer:
    image: dockette/adminer
    restart: always
    hostname: "adminer.local"
    ports:
      - 8090:80
    container_name: golang-docker-adminer

networks:
  default:
    external:
      name: my-project

volumes:
  golang-docker-data:
    